server:
  port: 31000
spring:
  application:
    name: wk‐service‐manage‐cms‐client
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: wk_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
wk:
  mq:
    queue: ${qn:queue_cms_postpage_01}
    routingKey: ${rk:5a751fab6abb5044e0d19ea1}